config/routes.rb
Rails.application.routes.draw do

  resources :investor
  resources :account_histories do
    collection do
      post :deposit
      post :withdraw
      post :pool
      get :pool_amount
    end
  end
  #resources :investor
 # get 'investor' => 'investor#index'
  params = { controller: 'investor', action: 'index' }

  resources :investments
  resources :memberships
  resources :authorships
  resources :application

  devise_for :users

  resources :users, only: [:show ] do
    collection do
      post :search
    end
  end
  #resources :users, defaults: {format: 'xml'} ,only: [:show , :index]
  #resources :users ,only: [:index]

  #Researcher
  get '/researcher-project' => 'projects#researcherViewProjects',as: 'researcher_project'
  get '/request' => 'projects#requestsByProject'
  get '/Researcher' => 'projects#mainResearcher'
  get '/researcher' => 'projects#mainResearcher'
  get '/edit_project/id*:id'=> 'projects#editProject'
  get '/accountHistory' => 'projects#accountHistory'
  post '/update/:id' => 'projects#update_project',as: "update_project"

  #Investor
  # get '/investor-project' => 'projects#investorViewProjects'
  get '/viwe-request' => 'projects#viewRequests'
  get '/investor-account' => 'projects#viewAccount'
  get '/open-trades' => 'projects#viewOpenTrade'
  get '/trade-history' => 'projects#viewTradeHistory'
  get '/Investor' => 'projects#mainInvestor'
  get '/user/investor' => 'projects#mainInvestor'
  get '/accounthistory' => 'projects#accountHistory'

  #Researcher
  get '/editProject' => 'projects#edit'
  get '/new' => 'projects#new'
  get '/researcher_detail/id*:id' => 'projects#researchertDetail',as: "researchertDetail"

  #Investor
  get '/investor_detail/id*:id'=> 'projects#investor_projectDetail'

  #user
  get '/edit-profile/id*:id' => 'users#edit_profile'
  get 'user-logout' => 'devise/sessions#destroy'
  get 'registrations' => 'users#add'

  #shares
  post '/buy' => 'shares#buy'
  post '/sell' => 'shares#sell'

  resources :projects do
    member do
      get :add_member
      get :add_investor
    end
  end

  resources :annotations

  # root 'home#index'
  root 'projects#main'
  get 'main' => 'projects#main'

  namespace :api, defaults: {format: 'json'} do
    # /api/... Api::
    namespace :v1 do
      resources :projects
      resources :users
      resources :investments
      resources :authorships
      resources :memberships
      resources :logins  ,:only => [:create]
      resources :tokens
      resources :annotations
      resources :order_books
      resources :graphs, :only => [:index]
       end
  end

  get 'test' => 'projects#test'

#match ':controller(/:show(/:id(.:format)))' => 'projects#investor_projectDetail', via: [:get]

#match 'controller/do_it' => 'controller#do_it', :as => 'do_it'
  #get 'detail/:id', to: 'projects#show', as: 'detail'

end

app/models/project.rb
class Project < ActiveRecord::Base
  ## Associations

  has_many :authorships, dependent: :destroy
  has_many :authors, through: :authorships, dependent: :destroy, source: :user

  has_many :membership, dependent: :destroy
  has_many :members, through: :membership, dependent: :destroy, source: :user

  has_many :investment, dependent: :destroy
  has_many :investors, through: :investment, dependent: :destroy, source: :user

  has_many :membership
  has_many :authorship

  ## Validation
  #validates :title, presence: true
  #validates :description, presence: true
end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < ApplicationController
      respond_to :json

      # # Securing an API
      # http_basic_authenticate_with name: 'admin', password: 'password'

      def index
        respond_with Project.all
        #    cookies[:user_id]   = current_user.id

      end

      def show
        #if not Token.find_by(:user_id => params[:id] , :token => params[:token]) #&& Token.find_by(:token => params[:token])
         # render :json=> {:message=>" INCORRECT ID OR TOKEN "}
        #else
        #respond_with Project.all
        #end
        respond_with Project.find(params[:id])

      end

      def create
        current_user_id = request.env["HTTP_REFERER"].split("&").last.split("=").last.to_i
          @project = Project.create(:title => params[:title], :description=>params[:description] )
         if current_user.present?
           @project.authors << current_user
         else
          current_user = User.find_by_id(current_user_id)
          @project.authors << current_user
         end 
          respond_with   @project 
 
      end

      def update
        respond_with Project.update(params[:id], :title => params[:title], :description=>params[:description])
      end

      def destroy
        respond_with Project.destroy(params[:id])
      end

    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :load_selected_affiliate, only: [:requestsByProject]

  
  # 
  def main 
    if current_user
      if current_user && current_user.investor == true
        redirect_to user_investor_url
      else
        redirect_to researcher_url 
      end
    end
  end
  # 
  ## Add a member to the project
  def add_member
    @project = Project.find(params[:id])
    @project.members << User.find(params[:user_id])
    redirect_to @project
  end

  
  ## Add an investor to the project
  def add_investor
    @project = Project.find(params[:id])
    @project.investors << User.find(params[:user_id])
    redirect_to @project
  end      

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
    @project = Project.find_by_id(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    # binding.pry
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.authors << current_user
    
    if @project.save
      render @project

    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    #if @project.update(project_params)
    # redirect_to @project
    #else
    # render :edit
    #end
  end

  def details
    if @project.find(:id)
      redirect_to @project
    else
      redirect_to projects_url
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url
  end

  # def viewopentrade

  # end

  def submit_request
    @annotation = Annotation.new(annotation_params)
    @annotation.item_price_dup = params[:Item_Price]
    if @annotation.save!
      flash[:success] = "Request Submit Successfully"
      redirect_to root_path
    else
      flash[:error] = "Something Went Wrong"
      redirect_to Register_path
    end
  end
  
  def editProject
    @project = Project.find_by_id(params[:id])
  end

  def update_project
    @project = Project.find_by_id(params[:id])
    if @project.update(update_project_params)
      @project.reload
      flash[:success]="Project updated successfully."
      redirect_to researcher_project_path
    else
      flash[:error] = "Project not updated."
      redirect_to request.referer
    end

  end


  def  requestsByProject
    @affilates = [] 
    Project.find_each do |project|
      @affilates << { title: project.title, id: project.id }
      if project.authors.last == current_user && current_user.researcher == true
        @affilates << { title: project.title, id: project.id }
      end
    end
  end


  def researchertDetail
    @project = Project.find_by_id(params[:id])
    @annotation = Annotation.where(Project_Select: Project.find_by_id(params[:id]).title, annotation_creator_id: current_user.id).paginate(:page => params[:page], :per_page => 4).order('id DESC') rescue nil
    @member = Project.find_by_id(params[:id]).members rescue nil
  end

  def accountHistory
    @history = current_user.account_histories.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')  rescue nil
  end

  def viewOpenTrade
    @open_trade = Share.where(is_trade_open: true) rescue nil
  end

  def viewTradeHistory
    #@close_trade = Share.where(is_trade_open: false) rescue nil  
    @close_trade = Share.all rescue nil
  end

  def mainInvestor
    
    @client = IEX::Api::Client.new(publishable_token: 'sk_b9257341ee8e443f9e0781c7f466db4f')
    @open_trade = Share.where(is_trade_open: true).paginate(:page => params[:page], :per_page => 4).order('id DESC') rescue nil
  end

  def researcherViewProjects
    @project=[];
    Project.all.each do |x|
      if x.authors.last == current_user && current_user.researcher == true
        @project << x    
      end  
    end    
    @project.paginate(:page => params[:page], :per_page => 4).order('id DESC') rescue nil
  end

  def mainResearcher
    @project=[];
    Project.all.each do |x|
      if x.authors.last == current_user && current_user.researcher == true
        @project << x    
      end  
    end    
    @project.paginate(:page => params[:page], :per_page => 4).order('id DESC') rescue nil
  end
 

  private

  def load_selected_affiliate
    @selected_affiliate = Project.find_by(id: params[:affiliate_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    # binding.pry
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params[:project].permit(:title, :description)
  end

  def update_project_params
    params.permit(:title, :description)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def project_description
    Project.find_by_id(params[:id]).description.capitalize  rescue nil
	end

	def find_project_created_at
    Project.find_by_id(params[:id]).created_at.localtime rescue nil
	end

	def find_project_title
    Project.find_by_id(params[:id]).try(:title) rescue nil
  end

  # def principal principal
  #   stocks = StockQuote::Stock.quote("aapl").as_json
  #   principal > stocks["latest_price"] ? (principal/stocks["latest_price"]) : principal == 0 ? (stocks["latest_price"]/1) : (stocks["latest_price"]/principal)
  # end

  def open_trade_count
    @open_count = Share.where(is_trade_open: true).count
    @open_count.present? ? @open_count : 0
  end

  def close_trade_count
    @close_count = Share.where(is_trade_open: false).count
    @close_count.present? ? @close_count : 0
  end

  def total_trade_count
    @total_count = Share.all.count
    @total_count.present? ? @total_count : 0
  end

  def dividend (grant, client)
    begin
      stocks = client.quote("aapl")
      fa = Annotation.where(item_price_dup: 0).pluck(:item_price).compact.sum rescue 1
      @dividend = (((stocks.latest_price/fa)/grant)*100).round(4)
      @dividend.nan? ?  0 : @dividend 
    rescue
      @dividend  = 0
    end
  end

  def profit_loss(invesment_principal, client)
    begin
      stocks = client.quote("aapl")
      fa = Annotation.where(item_price_dup: 0).pluck(:item_price).compact.sum rescue 1
      @profit_loss = (((stocks.latest_price/fa)/invesment_principal)*100).round(4)
      @profit_loss.finite? ?  @profit_loss : 0
    rescue
      @profit_loss = 0
    end
  end

  def find_project_creator
    if Project.find_by_id(params[:id]).authors
      Project.find_by_id(params[:id]).authors.last.first_name.capitalize + ' ' + Project.find_by_id(params[:id]).authors.last.last_name.capitalize
    end
  end
  
  
  def account_dividend(account)

    if account
      amount = account.amount 
      @client = IEX::Api::Client.new(publishable_token: 'sk_b9257341ee8e443f9e0781c7f466db4f')
      dividend(account.amount, @client)
      if @dividend > 0
        per = @dividend * amount
        amount = per/100
      end
      
      if  Date.today == account.date.to_date
        if account.durations == 'quarterly'
          date = Date.today + 3.months
        else
          date = Date.today + 1.year
        end
        
        
        account.update(date: date, dividend: @dividend)
      else
        account.update(dividend: @dividend)
      end
    end
    return account.try(:dividend)
  end
  
  def stock_cal_price(client)
    begin
      stocks = client.quote("aapl")
      fa = Annotation.where(item_price_dup: 0).pluck(:item_price).compact.sum rescue 1
      @total_price = stocks.latest_price/fa
    rescue
      @total_price = 0
    end
    return @total_price
  end
  
  def total_profit(trade, client)
    pl =  profit_loss(trade.investment_principal, client)
    invest =  trade.investment_principal.to_f
    total =  invest + (invest * pl)
    if total > 0
      total = total.round(2)
    end
    return total
  end
  
  def total_gain(account)
    total = account.dividend
    if account.amount > 0
      total = (account.amount * 2) + total
    end
    return total
  end
  
  
end

app/views/projects/accountHistory.html.erb
<section id="main-content">
    <section class="wrapper">
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <meta name="description" content="">
                <meta name="author" content="Mosaddek">
                <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
            </head>
            <body>
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">
                                Account History 
                            </header>
                            <div class="panel-body">
                                <div class="adv-table">
                                    <table cellpadding="0" cellspacing="0" border="0" 
                                           class="table table-striped table-condensed">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th style="text-align: center;">Name</th>
                                                <th style="text-align: center;">Date</th>
                                                <th style="text-align: center;">Market</th>
                                                <th style="text-align: center;">Duration</th>
                                                <th style="text-align: center;">Dividend</th>
                                                <th style="text-align: center;">Balance</th>
                                                 <th style="text-align: center;">Total Gain</th>
                                                <th style="text-align: center;">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody id="trade_history">
                                            <% @history.each do |history|%>
                                              <tr>
                                                  <td style="text-align: center;"><input type="checkbox" name="account" id="test" class="amit" value="<%= history.id%>"></td>
                                                  <td style="text-align: center;"><%= history.grant %></td>
                                                  <td style="text-align: center;"><%= history.date.strftime("%d-%m-%Y") %></td>
                                                  <td style="text-align: center;"><%= history.market%></td>
                                                  <td style="text-align: center;"><%= history.durations %></td>

                                                  <td style="text-align: center;">
                                                      <%= account_dividend(history) %>%
                                                  </td>
                                                  
                                                  <td style="text-align: center;">$<%= history.amount %></td>
                                                  <td style="text-align: center;">$<%= total_gain(history) %></td>
                                                  
                                                  <td style="text-align: center;">
                                                      <a class='btn btn-shadow btn-primary deposit1'  href="#smart-modal-deposit" data-toggle="modal" data-id="<%= history.id %>">Deposit</a> 
                                                      <a  class='btn btn-shadow btn-primary withdraw1'  href="#smart-modal-withdraw" data-toggle="modal" data-id="<%= history.id %>">Withdrawl </a>
                                                      <a  class='btn btn-shadow btn-primary pool1'  href="#smart-modal-pool" data-toggle="modal" data-id="<%= history.id %>"
                                                          >Pool </a>
                                                  </td>
                                              </tr>
                                            <% end if @history.present? %>
                                        </tbody>
                                    </table>
                                    <div>
                                        <a class='btn btn-shadow btn-primary deposit'  href="#smart-modal-deposit-account" data-toggle="modal">Deposit</a>
                                    </div>
                                    <div class="digg_pagination">
                                        <%= will_paginate @history rescue nil  %>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
    </section>
    <%= render 'partials/modals' %>  
    <!--main content end-->
</body>
</html>
</section>
</section>
<!-- js placed at the end of the document so the pages load faster -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/jszip.js"></script>
<script src="/assets/investor/viewRequests.js"  type="text/javascript" /></script>

<script type="text/javascript">
  var today = new Date().toISOString().split('T')[0];
  document.getElementsByName("date")[0].setAttribute('min', today);

  $('[id^=test]').click(function () {
      if ($(this).is(":checked")) {
          $(this).addClass('red');
      } else {
          $(this).removeClass('red');
      }
      var values = [];
      $('.red').each(function () {
          values.push(this.value);
      });
      //use values after the loop
      $('#pool_value').val(values);
  });

  $('.deposit1').click(function () {
      var my_id_value = $(this).data('id');
      $("#deposit_id").val(my_id_value);
  });

  $('.withdraw1').click(function () {
      var my_id_value = $(this).data('id');
      $("#withdrawl_id").val(my_id_value);
  });

  $(".pool1").click(function () {
      $.ajax({
          type: "get",
          url: "/account_histories/pool_amount",
          data: {
              id: $("#pool_value").val()
          },
          success: function (result) {
              console.log(result);
          },
          error: function (result) {
              alert('error');
          }
      });
  });


</script>

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', :back

app/views/projects/main.haml
- if !current_user 
  %html
    %head
      %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
      %link{:charset => "utf-8", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", :media => "screen", :rel => "stylesheet"}/
      %link{:charset => "utf-8", :href => "/assets/style_index.css", :media => "screen", :rel => "stylesheet"}/
    %body.image_bg
      .preload-bg
        .wrapp
          %div
        .container.colaborate
          .row
            .col-md-6.top-50.bottom-10
              .logo.bottom-30
          .row.txt-white
            .col-md-6.col-md-push-3
              %h1.bottom-30 Welcome, happy you made it.
              %p.bottom-30
                Elmhurst is a 501(c)3 philanthropic investment bank that provides financial services exclusively to nonprofits and their affiliates. In a world of bureaucratic loopholes, unreliable sources of financing, and unclear private accountability, Elmhurst is transparent, reliable, and seamless.
          .row
            .col-md-12.bottom-10
              %a.button.pushed.btn-primary.expand{:href => "/users/sign_in", :name => "button"} Investors
              %a.button.pushed.btn-primary.expand{:href => "/users/sign_in", :name => "button"} Nonprofits
          .row
            .col-md-12.bottom-10
              %a.button.pushed.expand{:href => "/users/sign_up", :name => "button"} SignUp

app/views/projects/new.html.haml

= render 'form'


app/views/projects/researchertDetail.html.erb
<section id="main-content">
    <section class="wrapper">
        <div id="projectDetailsViewModel">
            <div class="row state-overview">
                <div class="col-md-6 ">
                    <section class="panel">
                        <div class="symbol terques small-symbol">
                            <i class="icon-file"></i>
                        </div>
                        <div  class="value small-value">
                            <h1 class="count"><%= find_project_title %></h1>
                            <div class="row ">
                                <p>Created by  
                                    <a ><%= find_project_creator %>
                                    </a>
                                </p>
                                <span>Created_at <%= find_project_created_at  %></span>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="col-md-3 ammount">
                    <section class="panel">
                        <div class="ammount-head">
                            <h5>Request amount</h5>
                        </div>
                        <footer class="ammount-footer">
                            <h4>$<%= annotation_item_price_sum %></h4>
                        </footer>
                    </section>
                </div>
                <div class="col-md-3 ammount">
                    <section class="panel">
                        <div class="ammount-head">
                            <h5>Purchasing Power</h5>
                        </div>
                        <footer class="ammount-footer">
                            <h4>$<%= purchasing_power %></h4>
                        </footer>
                    </section>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <section class="panel">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <h4>Project Description</h4>
                                    <p><%= project_description %></p>
                                </div>
                                <div class="col-md-4">
                                    <h4>Project Members</h4>
                                    <ul class="list-group">
                                        <div class="list-group-item" >
                                            <% @member.each do |member|%>
                                              <div class="col-md-12">
                                                  <div>
                                                      <%= member.first_name.capitalize + ' ' + member.last_name.capitalize %>
                                                      <a data-confirm="Are you sure delete?" 
                                                         rel="nofollow" data-method="delete" 
                                                         href="<%= membership_url(id: member.try(:id), project_id: @project.id)%>">
                                                          <i class="icon-remove" style="color: red"> </i> 
                                                      </a>
                                                  </div>
                                              </div>

                                            <% end if @member.present? %>
                                        </div>

                                        <li class="list-group-item" style="margin-top: -2px;">
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <a class="btn btn-white btn-block" style="color: #000" href="#smart-modal-user" data-toggle="modal"><i class="icon-plus"></i> Add a Member </a>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <div>
                <div class="row">
                    <div class="col-xs-12">
                        <section class="panel">
                            <header class="panel-heading">
                                Project Requests 
                                <a  href= <%= "/request?affiliate_id=#{@project.id}" %> style="margin-left: 790px;width: 100px;" class="btn btn-white request">
                                    <i class="icon-plus-sign"></i>
                                    Request
                                </a>
                            </header>
                            <div class="panel-body">
                                <div class="adv-table">
                                    <table cellpadding="0" cellspacing="0"  class="display table" style="width: 100%; border:0 ">
                                        <thead>
                                            <tr>
                                                <th  style="width: 20%;  text-align: center;">Item</th>
                                                <th  style="width: 20%;  text-align: center;">Amount</th>
                                                <th  style="width: 20%;  text-align: center;">Full Fill</th>
                                                <th  style="width: 20%;  text-align: center;">Date</th>
                                                <th  style="width: 10%;  text-align: center;">Edit</th>
                                                <th  style="width: 10%;  text-align: center;">Delete</th>
                                            </tr>
                                        </thead>
                                        <tbody >
                                            <% @annotation.each do |annotation| %>
                                              <tr>
                                                  <td style="width: 22%; text-align: center;">
                                                      <%= annotation.Item_Name %>
                                                  </td>
                                                  <td  style="width: 25%; text-align: center;"> <%= annotation.Item_Price %></td>
                                                  <td  style="width: 20%; text-align: center;">
                                                      <% if annotation.date %>
                                                        <%= annotation.date.strftime("%d/%m/%Y") %>
                                                      <% end %>
                                                  </td>
                                                  <td  style="width: 15%; text-align: center;"><%= annotation.created_at.strftime("%d/%m/%Y") %></td>
                                                  <td style="text-align: center;"><a href= "<%= edit_annotation_url(annotation)%>"  class="btn btn-info btn-xs">&puncsp; <i class="icon-info"> </i> &puncsp;</a></td> 
                                                  <td style="text-align: center;">
                                                      <a data-confirm="Are you sure delete?" rel="nofollow" data-method="delete" href="<%= annotation_url(id: annotation.try(:id), Project_Select:@project.id)%>" class="btn btn-info btn-xs" style="background-color: #af0808; border-color: #af0808">&puncsp; 
                                                          <i class="icon-trash"> </i> &puncsp;
                                                      </a>
                                                  </td>
                                              </tr>
                                            <% end if @annotation.present? %>
                                        </tbody>
                                    </table>
                                    <div class="digg_pagination">
                                        <%= will_paginate @annotation rescue nil  %>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
    </section>
</section>



<div role="dialog" class="modal" id="smart-modal-user" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                <h4 class="modal-title">Add Member</h4>
            </div>
            <div class="modal-body">

                <%= form_for :users, url: search_users_url , :remote => true do |f| %> 
                  <div class="row">
                      <div class="col-sm-12">
                          <input type="hidden" name="project_id" value="<%= @project.id%>" />
                          <div class="form-group">
                              <label for="Buy Share">Search User By Email</label>
                              <input class="form-control" name="email" type="email" placeholder="Search User By Email"  required="">
                          </div>
                          <div class="form-group">
                              <button class="btn btn-primary btn-shadow btn-block "> Search </button>
                          </div>
                      </div>
                  </div>
                <% end %>
                <div class="row">
                    <div id="users_list"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/assets/addMember.js"  type="text/javascript" /></script>